services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`${FRONTEND}`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls=true"
      - "traefik.http.routers.www.tls.certresolver=le"
      - "traefik.http.services.www.loadbalancer.server.port=80"
    networks:
      - traefik-net
  bird-api:
    build: .
    container_name: bird-api
    environment:
      AUTH_CODE: ${AUTH_CODE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    volumes:
      - ./datasets:/app/datasets
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true